######################################################################
# Automatically generated by qmake (3.0) ?? ????. 26 10:32:07 2018
######################################################################

TEMPLATE = app
TARGET = QT
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT+=widgets